#!node
import { getNodeFS } from "@hoge1e3/sfile";
import {main} from "./cmd.js";
import { Shell } from "./shell.js";
import { setFS } from "./store-file.js";
const FS=await getNodeFS();
setFS(FS);
const shell=new Shell(process.cwd(),FS);
//console.log("process.argv",process.argv);
main.call(shell, ...process.argv.slice(2));